apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - image: docker.io/wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: MARIADB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: MARIADB_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: MARIADB_DATABASE

        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
        - name: apache-state
          mountPath: /var/lock/apache2
        - name: apache-state
          mountPath: /var/run/apache2
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-data
      - name: apache-state
        emptyDir: {}
