apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: mariadb
resources:
- deployment.yaml
- pvc.yaml
- service.yaml

secretGenerator:
- envs:
  - mariadb-credentials.env
  name: mariadb-credentials
